repos:
  - repo: https://github.com/pycqa/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        language_version: python3
        args: [
          '--in-place',
          '--remove-all-unused-imports',
          '--ignore-init-module-imports'
        ]
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3
        args: ['--profile', 'black', '--filter-files']
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
