name: Run test suite

on:
  push:
    branches:
      - '**'
      - '!main' # We ignore main because the deploy workflow runs tests

jobs:
  run_tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          PIP_NO_BINARY=parsons PARSONS_LIMITED_DEPENDENCIES=true pip install .
          pip install -r requirements-dev.txt

      - name: Test with pytest
        run: |
          python -m pytest
          
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-results
          path: junit/test-results.xml
        # Use always() to always run this step to publish test results
        # when there are test failures
        if: ${{ always() }}
